[phases.setup]
nixPkgs = ['python310', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'streamlit run app.py --server.port=$PORT --server.address=0.0.0.0'
